MyCRMProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('main/', include('crmproject.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crmproject/urls.py
from django.conf import settings
from django.urls import path, include
from crmproject import views


interaction_urls = [
    path('', views.AboutInteractionView.as_view(), name='about_interaction'),
    path('update/', views.UpdateInteractionView.as_view(), name='update_interaction'),
    path('delete/', views.DeleteInteractionView.as_view(), name='delete_interaction'),
]


profile_urls = [
    path('', views.MyProfileView.as_view(), name='profile'),
    path('update/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('delete/', views.DeleteProfileView.as_view(), name='delete_profile'),
    path('my_interaction/', views.InfoAboutMyInteractionView.as_view(), name='my_interaction'),
    path('create_company/', views.CreateCompanyView.as_view(), name='create_company'),
]


projects_urls = [
    path('', views.ProjectInfoView.as_view(), name='about_project'),
    path('create_interaction/', views.CreateInteractionView.as_view(), name='create_interaction'),
    path('update/', views.UpdateProjectView.as_view(), name='update_project'),
    path('delete/', views.DeleteProjectView.as_view(), name='delete_project'),
    path('interaction/<int:interaction_pk>/', include(interaction_urls)),
]


company_urls = [
    path('', views.InfoAboutCompanyView.as_view(), name='info'),
    path('update/', views.UpdateCompanyView.as_view(), name='update_company'),
    path('delete/', views.DeleteCompanyView.as_view(), name='delete_company'),
    path('create_project/', views.CreateProjectView.as_view(), name='create_project'),
    path('project/<int:project_pk>/', include(projects_urls)),
]


urlpatterns = [
    path('', views.AllCompanyView.as_view(), name='index'),
    path('info/<int:pk>/', include(company_urls)),
    path('profile/', include(profile_urls)),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.urls import path, include
from users import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.RegistrationView.as_view(), name='registration'),
]

crmproject/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from users.models import User
from ckeditor.fields import RichTextField


class Company(models.Model):
    """
    Model for Company in crmproject app.
    """
    name_of_company = models.CharField(max_length=50)
    director_name = models.CharField(max_length=20)
    director_surname = models.CharField(max_length=20)
    director_patronymic = models.CharField(max_length=20)
    about_company = RichTextField(blank=True, null=True)
    create_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=30)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='users/photos', default='', blank=True)

    class Meta:
        ordering = ('name_of_company',)

    def __str__(self):
        return self.name_of_company


class Phone(models.Model):
    """
    Model for Phone for inlineformset
    """
    phone_number = models.CharField(max_length=12, verbose_name='Номер телефона')
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return f'Phone: {self.phone_number} | Company: {self.company}'


class Email(models.Model):
    """
    Model for Email for inlineformset
    """
    email_address = models.EmailField(max_length=100, verbose_name='Email адрес')
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return f'Email: {self.email_address} | Company: {self.company}'


class Project(models.Model):
    """
    Model for Company Projects.
    """
    status_fields = (
        ('1', 'Completed'),
        ('2', 'Project under development'),
        ('3', 'Overdue')
    )
    name = models.CharField(max_length=30, blank=False, null=False)
    description = RichTextField(max_length=500, blank=False, null=False)
    date_start = models.DateField(blank=False, null=False)
    date_end = models.DateField(blank=False, null=False)
    status = models.CharField(max_length=1, choices=status_fields)
    price = models.PositiveIntegerField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.company} | {self.name}'

    def get_absolute_url(self):
        return reverse('about_project', kwargs={'pk': self.company.pk,
                                                'project_pk': self.pk})


class Interaction(models.Model):
    """
    Model for interaction on project
    """
    communication_options = (
        ('1', 'Request'),
        ('2', 'Letter'),
        ('3', 'Website'),
        ('4', 'Company initiative')
    )
    rating_options = (
        ('1', 'Unacceptable'),
        ('2', 'Weak'),
        ('3', 'Good'),
        ('4', 'Very good'),
        ('5', 'Excellent')
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    communication_method = models.CharField(max_length=1, choices=communication_options)
    manager = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    description = RichTextField(max_length=200, blank=False, null=False)
    rating = models.CharField(max_length=1, choices=rating_options)
    publication_date = models.DateTimeField(auto_now_add=True, blank=False, null=False)

    def __str__(self):
        return f'Feedback: {self.manager}'

    def get_absolute_url(self):
        return reverse('about_interaction', kwargs={'pk': self.project.company.pk,
                                                    'project_pk': self.project.pk,
                                                    'interaction_pk': self.pk})

crmproject/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from django.views.generic.detail import SingleObjectMixin, DetailView
from crmproject.forms import FormUpdateProfile, CreateCompanyForm, CompanyPhoneFormSet, \
    CompanyEmailFormSet, CompanyPhoneForUpdate, CompanyEmailForUpdate, UpdateCompanyForm, CreateProjectForm, \
    UpdateProjectForm, CreateInteractionForm
from crmproject.models import Company, Project, Interaction
from users.models import User


class MyProfileView(LoginRequiredMixin, DetailView):
    """
    View for view the user's personal settings
    """
    model = User
    template_name = 'crmproject/profile.html'

    def get_object(self, queryset=None):
        """
        Redefinition method

        :param queryset: None
        :return: self.request.user
        """
        return self.request.user


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """
    View for update user information
    """
    template_name = 'crmproject/update_profile.html'
    model = User
    form_class = FormUpdateProfile

    def get_object(self, queryset=None):
        """
        Redefinition method

        :param queryset: None
        :return: self.request.user
        """
        return self.request.user

    def get_success_url(self):
        """
        Redefinition method

        After updating information about yourself, the user will be redirected to profile
        :return: reverse_lazy('profile')
        """
        return reverse_lazy('profile')


class DeleteProfileView(DeleteView):
    """
    View for delete user
    """
    model = User
    success_url = reverse_lazy('home')
    template_name = 'crmproject/profile_delete.html'

    def get_object(self, queryset=None):
        """
        Redefinition method

        :param queryset: None
        :return: self.request.user
        """
        return self.request.user


class InfoAboutMyInteractionView(LoginRequiredMixin, SingleObjectMixin, ListView):
    """
    View for show my interactions
    """
    model = Interaction
    template_name = 'crmproject/my_interaction.html'
    paginate_by = 5

    def get(self, request, *args, **kwargs):
        """
        Redefinition method

        Get a queryset of all interactions into a variable 'self.object'
        :param request: request
        :param args: *
        :param kwargs: **
        :return: super().get(request, *args, **kwargs)
        """
        self.object = Interaction.objects.all()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        """
        Redefinition method

        Filtering and showing the user a list of his interactions
        :return: Interaction.objects.filter(manager=self.request.user)
        """
        return Interaction.objects.filter(manager=self.request.user)


class AllCompanyView(LoginRequiredMixin, ListView):
    """
    View for list all available companies with pagination
    """
    model = Company
    template_name = 'crmproject/index.html'
    context_object_name = 'companys'
    paginate_by = 6

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'alf')
        if ordering == 'alf':
            return 'name_of_company'
        else:
            return '-name_of_company'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.annotate(cnt=Count('project'))
        return qs


class InfoAboutCompanyView(LoginRequiredMixin, SingleObjectMixin, ListView):
    """
    View for view detailed information about the company
    """
    model = Project
    template_name = 'crmproject/info_about_company.html'
    paginate_by = 3

    def get(self, request, *args, **kwargs):
        """
        Redefinition method

        In a variable self.object we get queryset
        :param request: request
        :param args: *
        :param kwargs: **
        :return: super().get(request, *args, **kwargs)
        """
        self.object = Company.objects.get(pk=self.kwargs['pk'])
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        qs = Project.objects.all()
        qs = qs.annotate(cnt=Count('interaction'))
        return qs


class CreateCompanyView(LoginRequiredMixin, CreateView):
    """
    View for create company information
    """
    model = Company
    form_class = CreateCompanyForm
    template_name = 'crmproject/create_company.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        """
        Redefinition method

        The method displays 2 additional forms for adding phone numbers and email addresses
        :param kwargs: **
        :return: context
        """
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            contact_phone = CompanyPhoneFormSet(self.request.POST)
            contact_email = CompanyEmailFormSet(self.request.POST)
        else:
            contact_phone = CompanyPhoneFormSet()
            contact_email = CompanyEmailFormSet()
        context.update(
            {
                'phone_form': contact_phone,
                'email_form': contact_email
            }
        )
        return context

    def form_valid(self, form):
        """
        Redefinition method

        Checking forms for validity
        :param form: form
        :return: super().form_valid(form)
        """
        form.instance.user = self.request.user
        contact_phone = CompanyPhoneFormSet(self.request.POST)
        contact_email = CompanyEmailFormSet(self.request.POST)
        if contact_email.is_valid() and contact_phone.is_valid():
            self.obj = form.save()
            contact_email.instance = self.obj
            contact_phone.instance = self.obj
            contact_email.save()
            contact_phone.save()
        else:
            return self.form_invalid(form)

        return super().form_valid(form)


class UpdateCompanyView(UserPassesTestMixin, UpdateView):
    """
    View for update company information
    """
    template_name = 'crmproject/update_company.html'
    model = Company
    form_class = UpdateCompanyForm

    def get_success_url(self):
        """
        Redefinition method

        After updating the company information, the user will be redirected to the company information page
        :return: reverse_lazy('info', kwargs={'pk': self.kwargs['pk']})
        """
        return reverse_lazy('info', kwargs={'pk': self.kwargs['pk']})

    def test_func(self):
        """
        Redefinition method

        Only the user who created the company can update information about it
        :return: True or False
        """
        if self.request.user != self.get_object(queryset=Company.objects.all()).user:
            return False
        return True

    def get_context_data(self, **kwargs):
        """
        Redefinition method

        Shows the user data from the database in forms to update information about companies
        :param kwargs: **
        :return: context
        """
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            contact_phone = CompanyPhoneForUpdate(self.request.POST, instance=self.object)
            contact_email = CompanyEmailForUpdate(self.request.POST, instance=self.object)
        else:
            contact_phone = CompanyPhoneForUpdate(instance=self.object)
            contact_email = CompanyEmailForUpdate(instance=self.object)
        context.update(
            {
                'phone_form': contact_phone,
                'email_form': contact_email
            }
        )
        return context

    def form_valid(self, form):
        """
        Redefinition method

        Checking forms for validity
        :param form: form
        :return: super().form_valid(form)
        """
        form.instance.user = self.request.user
        contact_phone = CompanyPhoneForUpdate(self.request.POST, instance=self.object)
        contact_email = CompanyEmailForUpdate(self.request.POST, instance=self.object)
        if contact_email.is_valid() and contact_phone.is_valid():
            form.save()
            contact_email.save()
            contact_phone.save()
        else:
            return self.form_invalid(form)

        return super().form_valid(form)


class DeleteCompanyView(LoginRequiredMixin, DeleteView):
    """
    View for delete company
    """
    model = Company
    success_url = reverse_lazy('index')
    template_name = 'crmproject/company_delete.html'


class ProjectInfoView(LoginRequiredMixin, SingleObjectMixin, ListView):
    """
    View for view detailed information about the projects
    """
    model = Interaction
    template_name = 'crmproject/info_about_project.html'
    paginate_by = 3

    def get(self, request, *args, **kwargs):
        """
        Redefinition method

        In a variable self.object we get queryset
        :param request: request
        :param args: *
        :param kwargs: **
        :return: super().get(request, *args, **kwargs)
        """
        self.object = Project.objects.get(pk=self.kwargs['project_pk'])
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        """
        Redefinition method

        We get a queryset with filtered interactions for each project
        :return: Project.objects.filter(company=self.kwargs['project_pk'])
        """
        return Interaction.objects.filter(project=self.kwargs['project_pk'])


class CreateProjectView(LoginRequiredMixin, CreateView):
    """
    View for Create info about project
    """
    model = Project
    form_class = CreateProjectForm
    template_name = 'crmproject/create_project.html'

    def get_success_url(self):
        """
        Redefinition method

crmproject/templates/crmproject/company_delete.html
{% extends 'base.html' %}

{% block title  %}Delete profile{% endblock %}

{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    <div class="text-center">
        <form method="post">
            {% csrf_token %}
            <h4>Are you sure you want to delete company: "<span class="text-danger">{{ company.name_of_company }}</span>"?</h4><br>
            <input class="btn mb-3 btn-success btn-sm" role="button" style="width: 7rem" type="submit" value="Confirm"><br>
            <a class="btn mb-3 btn-secondary btn-sm" role="button" style="width: 7rem" href="{% url 'info' pk=company.id %}">Back</a>
        </form>
    </div>
{% endblock %}

crmproject/templates/crmproject/create_company.html
{% extends 'base.html' %}

{% block title %}
    Create company
{% endblock %}


{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    {% include 'includes/form_for_create_and_update_company.html' %}
{% endblock %}

crmproject/templates/crmproject/create_interaction.html
{% extends 'base.html' %}

{% block title %}
    Create interaction
{% endblock %}


{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    {% include 'includes/form_for_create_and_update_interaction.html' %}
{% endblock %}

crmproject/templates/crmproject/create_project.html
{% extends 'base.html' %}

{% block title %}
    Create project
{% endblock %}


{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    {% include 'includes/form_for_create_and_update_project.html' %}
{% endblock %}

crmproject/templates/crmproject/index.html
{% extends 'base.html' %}

{% load url_replace_tags %}

{% block title %}
    Main page
{% endblock %}


{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    <a class="text-success" href="?ordering=alf">sort_by_alphabet</a>
    <a class="text-danger" href="?ordering=-alf">sort_by_-alphabet</a>

    {% for company in companys %}
        <div class="list-group">
            <a href="{% url 'info' pk=company.pk %}"
               style="background-color: #F5F5F5; font-size: 24px;"
               class="list-group-item shadow m-1 text-center text-uppercase">
                <p>&#171; {{ company.name_of_company }} &#187;</p>
                {% if company.cnt > 1 %}
                    <p style="font-size: 12px; color: #2e4053;">The company has <strong><em>{{ company.cnt }}</em></strong> projects </p>
                {% elif company.cnt == 1 %}
                    <p style="font-size: 12px; color: #2e4053;">The company has {{ company.cnt }} project </p>
                {% else %}
                    <p style="font-size: 12px; color: #2e4053;">The company has no projects yet </p>
                {% endif %}
            </a>
        </div>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination justify-content-center">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">Preview</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?{% url_replace request 'page' page_obj.next_page_number %}">Next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

crmproject/templates/crmproject/info_about_company.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
    Detail {{ company.name_of_company }}
{% endblock %}


{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    {% thumbnail company.photo '250x250' crop='center' as im %}
        <img class="" style="position: absolute; top: 195px; left: 10px" src="{{ im.url }}" alt="Company photo">
    {% endthumbnail %}

    <div>
        <p style="position: relative; left: 300px"><span class="h4">Name of company:</span> <span style="font-size: 20px; color: #800000">{{ company.name_of_company }}</span></p>
        <p style="position: relative; left: 300px"><span class="h6">Name of diretcor:</span> <span style="font-size: 20px; color: #800000">{{ company.director_name }}</span></p>
        <p style="position: relative; left: 300px"><span class="h6">Surname of director:</span> <span style="font-size: 20px; color: #800000">{{ company.director_surname }}</span></p>
        <p style="position: relative; left: 300px"><span class="h6">Create date:</span> <span style="font-size: 20px; color: #800000">{{ company.create_at }}</span></p>
        <p style="position: relative; left: 300px"><span class="h6">Location:</span> <span style="font-size: 20px; color: #800000">{{ company.location }}</span></p>
        {% for phone in company.phone_set.all %}
            <p style="position: relative; left: 300px"><span class="h6">Phone number:</span> <span style="font-size: 20px; color: #800000">{{ phone.phone_number }}</span></p>
        {% endfor %}
        {% for email in company.email_set.all %}
            <p style="position: relative; left: 300px"><span class="h6">Email:</span> <span style="font-size: 20px; color: #800000">{{ email.email_address }}</span></p>
        {% endfor %}
        {% if company.update_at %}
            <p style="position: relative; left: 300px"><span class="h6">Edited:</span> <span style="font-size: 20px; color: dimgrey">{{ company.update_at }}</span></p>
        {% endif %}

        {% if user.is_staff and user == company.user%}
            <a class="btn mb-3 btn-warning btn-sm" role="button"
               style="position: relative; width: 9rem;left: 300px;"
               href="{% url 'update_company' pk=company.id%}">Update</a>

            <a class="btn mb-3 btn-danger btn-sm" role="button"
               style="position: relative; width: 9rem;left: 300px;"
               href="{% url 'delete_company' pk=company.id%}">Delete</a>
        {% endif %}

        <h3 class="text-center">Description</h3>
        <p>{{ company.about_company | safe }}</p>
    </div>

    <h3 class="text-center mb-3">Company's projects</h3>
    {% if company.project_set.all %}
        {% include 'includes/add_project_button.html' %}

        {% for project in object_list %}
                <div class="list-group mb-2">
                    <a href="{{ project.get_absolute_url }}"
                        {% if project.status == '1' %}
                            style="background-color: #EEFFF4; font-size: 20px;"
                        {% elif project.status == '2'%}
                            style="background-color: #FFFFDF; font-size: 20px;"
                        {% else %}
                            style="background-color: #FFDCCB; font-size: 20px;"
                        {% endif %}
                       class="list-group-item shadow m-1 text-center">
                        <p><span class="text-uppercase">&#171; {{ project.name }} &#187;</span></p>
                        {% if project.cnt > 1 %}
                            <p><span style="font-size: 13px; color: #2e4053;">There are <strong>{{ project.cnt }}</strong> interactions in total in the project</span></p>
                        {% elif project.cnt == 1 %}
                            <p><span style="font-size: 13px; color: #2e4053;">There is <strong>{{ project.cnt }}</strong> interaction in total in the project</span></p>
                        {% else %}
                            <p><span style="font-size: 13px; color: #2e4053;">The project has no interactions yet</span></p>
                        {% endif %}
                    </a>
                </div>
        {% endfor %}
    {% else %}
        {% include 'includes/add_project_button.html' %}

        <p class="text-center">This company has not completed any projects yet and has no projects in development</p>
    {% endif %}

    {% include 'includes/paginate.html' %}
{% endblock %}

crmproject/templates/crmproject/info_about_interaction.html
{% extends 'base.html' %}

{% block title  %}Feedback info{% endblock %}

{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    <div class="text-center">
        <p><span style="font-size: 14px;">{{ interaction.publication_date }}</span></p>
        <p><span style="font-size: 20px;">{{ interaction.project }}</span></p>
        <p>Manager: <span class="text-primary">{{ interaction.manager }}</span></p>
        {% include 'includes/communication method.html' %}
        {% include 'includes/rating.html' %}
        <p style="font-size: 20px;">&#11015; Feedback &#11015; <span>{{ interaction.description|safe }}</span></p>
    </div>

    {% if user.is_staff and user == interaction.project.company.user%}
    <a class="btn mb-3 btn-warning btn-sm" role="button"
       style="position: relative; width: 9rem; left: 493px;"
       href="{% url 'update_interaction' pk=interaction.project.company.pk project_pk=interaction.project.pk interaction_pk=interaction.pk %}">Update</a>

    <a class="btn mb-3 btn-danger btn-sm" role="button"
       style="position: relative; width: 9rem; left: 493px;"
       href="{% url 'delete_interaction' pk=interaction.project.company.pk project_pk=interaction.project.pk interaction_pk=interaction.pk %}">Delete</a>
    {% endif %}

{% endblock %}

crmproject/templates/crmproject/info_about_project.html
{% extends 'base.html' %}

{% block title  %}Project info{% endblock %}

{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    <div class="text-center">
        <p><span style="color: dimgrey; font-size: 15px;">Project name:</span> <span style="font-size: 17px;">{{ project.name }}</span></p>
        {% if user.is_staff %}
            <p><span style="color: dimgrey;">Budget:</span><br> <span class="text-decoration-underline" style="font-size: 17px;">{{ project.price }} $</span></p>
        {% endif %}
        {% if project.status == '1' %}
            <p><span style="color: dimgrey;">Status:</span> <span class="text-success" style="font-size: 17px;">Completed</span></p>
        {% elif project.status == '2' %}
            <p><span style="color: dimgrey;">Status:</span> <span class="text-warning" style="font-size: 17px;">Project under development</span></p>
        {% else %}
            <p><span style="color: dimgrey;">Status:</span> <span class="text-danger" style="font-size: 17px;">Overdue</span></p>
        {% endif %}
        <p><span style="color: dimgrey;">Description:</span><br> <span style="font-size: 17px;">{{ project.description|safe }}</span></p>
        <p><span style="color: dimgrey;">Start date:</span> <span style="font-size: 17px;">{{ project.date_start }}</span></p>
        <p><span style="color: dimgrey;">End date:</span> <span style="font-size: 17px;">{{ project.date_end }}</span></p>
    </div>

    {% if user.is_staff and user == project.user%}
    <a class="btn mb-3 btn-warning btn-sm" role="button"
       style="position: relative; width: 9rem; left: 493px;"
       href="{% url 'update_project' pk=project.company.pk project_pk=project.pk %}">Update project</a>

    <a class="btn mb-3 btn-danger btn-sm" role="button"
       style="position: relative; width: 9rem; left: 493px;"
       href="{% url 'delete_project' pk=project.company.pk project_pk=project.pk %}">Delete project</a>
    {% endif %}

    {% if user.is_staff %}
    <div>
        <p class="text-center h3 mt-4">Project feedback</p>
    </div>
        <a class="btn mb-3 btn-info btn-sm" role="button"
           style="position: relative; width: 9rem; left: 570px;"
           href="{% url 'create_interaction' pk=project.company.pk project_pk=project.pk %}">Add feedback</a>

    {% if not project.interaction_set.all %}
        <p class="text-center">The company currently has no reviews.</p>
    {% else %}
        {% for interaction in object_list %}
            <div class="list-group mb-2">
                <a href="{{ interaction.get_absolute_url }}" style="background-color: #F7F9FF;"
                   class="list-group-item shadow m-1 text-center">
                    {% include 'includes/communication method.html' %}
                    {% include 'includes/rating.html' %}
                    <p>{{ interaction.description|safe }}</p>
                    <p><span style="font-size: 14px;">{{ interaction.publication_date|date:"D d.m.y H:i" }}</span></p>
                </a>
            </div>
        {% endfor %}
        {% include 'includes/paginate.html' %}
    {% endif %}
    {% endif %}

{% endblock %}

crmproject/templates/crmproject/interaction_delete.html
{% extends 'base.html' %}

{% block title  %}Delete interaction{% endblock %}

{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    <div class="text-center">
        <form method="post"
              action="{% url 'delete_interaction' pk=interaction.project.company.pk project_pk=interaction.project.pk interaction_pk=interaction.pk %}?next={% url 'about_project' pk=interaction.project.company.pk project_pk=interaction.project.pk %}">
            {% csrf_token %}
            <h4>Are you sure you want to delete feedback?</h4><br>
            <input class="btn mb-3 btn-success btn-sm" role="button" style="width: 7rem" type="submit" value="Confirm"><br>
            <a class="btn mb-3 btn-secondary btn-sm" role="button" style="width: 7rem"
               href="{% url 'about_interaction' pk=interaction.project.company.pk project_pk=interaction.project.pk interaction_pk=interaction.pk %}">Back</a>
        </form>
    </div>
{% endblock %}

crmproject/templates/crmproject/my_interaction.html
{% extends 'base.html' %}


{% block title %}
    My interaction
{% endblock %}


{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    {% for interaction in object_list %}
            <div class="list-group mb-2">
                <a href="{{ interaction.get_absolute_url }}" style="background-color: #F7F9FF;"
                   class="list-group-item shadow m-1 text-center">
                    <p><span>{{ interaction.project }}</span></p>
                    {% include 'includes/communication method.html' %}
                    {% include 'includes/rating.html' %}
                    <p><span style="">{{ interaction.description|safe }}</span></p>
                </a>
            </div>
    {% endfor %}

    {% include 'includes/paginate.html' %}
{% endblock %}

crmproject/templates/crmproject/update_project.html
{% extends 'base.html' %}

{% block title %}
    Update company
{% endblock %}


{% block content %}
    {% include 'includes/header.html' %}

    {% include 'includes/finaly_navbar.html' %}

    {% include 'includes/form_for_create_and_update_project.html' %}
{% endblock %}